### PR TITLE
retrieve the content of file for yaml parsing

### PR DESCRIPTION
**Pull request by zephyr-thomas**

### CODE REVIEW

**Comment by nicodmf** [comment]
@Ocramius @beberlei it seems that yaml has two or three little problem https://github.com/doctrine/DoctrineCouchDBBundle/pull/53 https://github.com/doctrine/DoctrineCouchDBBundle/pull/48

Can we have more life on this pretty and usefull database  ?

**Comment by mikeSimonson** [comment]
@Ocramius Should we change the yaml requirement to < 3.0 . Do a bug fix release and then merge that code and feature release ?

**Comment by mikeSimonson** [comment]
supperseeded by #134

**Comment by mikeSimonson** [comment]
@zephyr-thomas Thanks

**Pull request closed without merging**
